# -*- coding: utf-8 -*-
"""helmet detection .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iXBbn68RWzWZHPamCq7DTGvKoOEXtE2n
"""

import os
os.listdir('/content')

import zipfile

zip_path = "/content/archive (1).zip"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall("/content/dataset")

print("Dataset extracted successfully!")

import os

os.listdir('/content/dataset')

import os
import random
import shutil

# Paths
images_path = "/content/dataset/images"
annotations_path = "/content/dataset/annotations"

# Create folders
train_images = "/content/dataset/train/images"
train_labels = "/content/dataset/train/labels"

valid_images = "/content/dataset/valid/images"
valid_labels = "/content/dataset/valid/labels"

os.makedirs(train_images, exist_ok=True)
os.makedirs(train_labels, exist_ok=True)

os.makedirs(valid_images, exist_ok=True)
os.makedirs(valid_labels, exist_ok=True)

# Get all images
images = [f for f in os.listdir(images_path)
          if f.endswith(".png") or f.endswith(".jpg")]

# Shuffle images
random.shuffle(images)

# Split ratio
split_index = int(0.8 * len(images))

train_files = images[:split_index]
valid_files = images[split_index:]

# Move train files
for image in train_files:

    shutil.copy(
        os.path.join(images_path, image),
        os.path.join(train_images, image)
    )

    xml_name = os.path.splitext(image)[0] + ".xml"

    shutil.copy(
        os.path.join(annotations_path, xml_name),
        os.path.join(train_labels, xml_name)
    )

# Move valid files
for image in valid_files:

    shutil.copy(
        os.path.join(images_path, image),
        os.path.join(valid_images, image)
    )

    xml_name = os.path.splitext(image)[0] + ".xml"

    shutil.copy(
        os.path.join(annotations_path, xml_name),
        os.path.join(valid_labels, xml_name)
    )

print("Dataset split completed successfully!")

import os
import xml.etree.ElementTree as ET

# Class mapping
classes = {
    "With Helmet": 0,
    "Without Helmet": 1
}

# Function to convert XML to YOLO
def convert_annotation(xml_path, output_path):

    tree = ET.parse(xml_path)
    root = tree.getroot()

    size = root.find("size")
    w = int(size.find("width").text)
    h = int(size.find("height").text)

    with open(output_path, "w") as f:

        for obj in root.findall("object"):

            class_name = obj.find("name").text

            if class_name not in classes:
                continue

            class_id = classes[class_name]

            xmlbox = obj.find("bndbox")

            xmin = int(xmlbox.find("xmin").text)
            xmax = int(xmlbox.find("xmax").text)
            ymin = int(xmlbox.find("ymin").text)
            ymax = int(xmlbox.find("ymax").text)

            # Convert to YOLO format
            x_center = ((xmin + xmax) / 2) / w
            y_center = ((ymin + ymax) / 2) / h

            box_width = (xmax - xmin) / w
            box_height = (ymax - ymin) / h

            f.write(
                f"{class_id} {x_center} {y_center} {box_width} {box_height}\n"
            )

# Convert train labels
train_labels_path = "/content/dataset/train/labels"

for file in os.listdir(train_labels_path):

    if file.endswith(".xml"):

        xml_path = os.path.join(train_labels_path, file)

        txt_path = os.path.join(
            train_labels_path,
            file.replace(".xml", ".txt")
        )

        convert_annotation(xml_path, txt_path)

# Convert valid labels
valid_labels_path = "/content/dataset/valid/labels"

for file in os.listdir(valid_labels_path):

    if file.endswith(".xml"):

        xml_path = os.path.join(valid_labels_path, file)

        txt_path = os.path.join(
            valid_labels_path,
            file.replace(".xml", ".txt")
        )

        convert_annotation(xml_path, txt_path)

print("XML to YOLO TXT conversion completed!")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/helmet.yaml
# 
# train: /content/dataset/train/images
# val: /content/dataset/valid/images
# 
# nc: 2
# 
# names:
#   0: helmet
#   1: no_helmet

!git clone https://github.com/ultralytics/yolov5

# Commented out IPython magic to ensure Python compatibility.
# %cd yolov5

!pip install -r requirements.txt

!python train.py --img 640 --batch 16 --epochs 50 --data /content/helmet.yaml --weights yolov5s.pt

!rm -rf /content/dataset/train/preprocessed_images
!rm -rf /content/dataset/valid/preprocessed_images

import cv2
import os
import numpy as np

# Input folders
train_input = "/content/dataset/train/images"
valid_input = "/content/dataset/valid/images"

# Output folders
# Overwrite original images directly
train_output = "/content/dataset/train/images"
valid_output = "/content/dataset/valid/images"

def preprocess_images(input_folder, output_folder):

    for image_name in os.listdir(input_folder):

        image_path = os.path.join(input_folder, image_name)

        img = cv2.imread(image_path)

        if img is None:
            continue

        # Convert to LAB color space
        lab = cv2.cvtColor(img, cv2.COLOR_BGR2LAB)

        l, a, b = cv2.split(lab)

        # CLAHE contrast enhancement
        clahe = cv2.createCLAHE(
            clipLimit=2.0,
            tileGridSize=(8, 8)
        )

        cl = clahe.apply(l)

        merged = cv2.merge((cl, a, b))

        enhanced = cv2.cvtColor(merged, cv2.COLOR_LAB2BGR)

        # Mild sharpening
        kernel = np.array([
            [0, -1, 0],
            [-1, 5, -1],
            [0, -1, 0]
        ])

        sharpened = cv2.filter2D(enhanced, -1, kernel)

        # Save processed image
        output_path = os.path.join(output_folder, image_name)

        cv2.imwrite(output_path, sharpened)

# Process training images
print("Processing train images...")
preprocess_images(train_input, train_output)

# Process validation images
print("Processing validation images...")
preprocess_images(valid_input, valid_output)

print("Preprocessing completed successfully!")

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/yolov5

!python train.py \
--img 640 \
--batch 16 \
--epochs 50 \
--data /content/helmet.yaml \
--weights yolov5s.pt

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/yolov5

!python detect.py \
--weights runs/train/exp5/weights/best.pt \
--img 640 \
--conf 0.25 \
--source /test.jpeg

print('/content/yolov5/runs/detect/exp')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/yolov5

!python detect.py \
--weights runs/train/exp5/weights/best.pt \
--img 640 \
--conf 0.25 \
--source /test.jpeg